var ColorName;
var totalAmount
var LastName
var emailId
var userName
var userId
var userAge
var phoneNo
var productName
var productNo
var ticketNo
var stopName
var vehicleNo
var trainNam
var backGrond
var textColor
var CarType
var CarModle
var cityName
var weatherCondition
var ColNo
var pinCdo
var dateoBirth
var laptopType
var laptopColor
var tableNumber
var paymentStatus
var SumResult
var CompanyName
var workingHours