const meds=[
{name:"Paracetamol",cat:"Pain Relief",price:45,img:"https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=90",purpose:"Commonly used for temporary relief of mild pain and fever.",guide:["Read the package label.","Use only as directed by the label or clinician.","Ask a pharmacist if you are unsure about interactions or suitability."]},
{name:"Ibuprofen",cat:"Pain Relief",price:65,img:"https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=90",purpose:"An NSAID commonly used for pain, inflammation and fever.",guide:["Check the label and warnings.","Ask a healthcare professional if you have questions about suitability.","Do not assume every pain medicine is appropriate for everyone."]},
{name:"Cetirizine",cat:"Cold & Flu",price:55,img:"https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=90",purpose:"An antihistamine commonly used for allergy symptoms.",guide:["Read the label.","Check warnings about drowsiness.","Ask a pharmacist if combining with other medicines."]},
{name:"ORS",cat:"Digestive",price:30,img:"https://images.unsplash.com/photo-1550572017-edd951aa8ca2?auto=format&fit=crop&w=800&q=90",purpose:"Oral rehydration solution can replace fluids and electrolytes during fluid loss.",guide:["Prepare exactly as directed on the product.","Use safe water and follow storage instructions.","Seek medical help when dehydration is severe or concerning."]},
{name:"Vitamin D",cat:"Vitamins",price:120,img:"https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=90",purpose:"A vitamin involved in normal bone and body functions.",guide:["Check the product strength.","Avoid assuming more is better.","Ask a clinician about supplementation when appropriate."]},
{name:"Vitamin C",cat:"Vitamins",price:110,img:"https://images.unsplash.com/photo-1616671276441-2f2c2f2c4e0e?auto=format&fit=crop&w=800&q=90",purpose:"An essential vitamin that supports normal body functions.",guide:["Follow product directions.","Prefer a balanced diet for everyday nutrition.","Ask before using high-dose supplements."]},
{name:"First Aid Kit",cat:"First Aid",price:399,img:"https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=800&q=90",purpose:"Demo first-aid supplies for basic home care.",guide:["Check expiry dates periodically.","Keep supplies organized and accessible.","For serious injuries, seek emergency medical care."]},
{name:"Cold Care",cat:"Cold & Flu",price:90,img:"https://images.unsplash.com/photo-1580281658628-9b8b3e2c5e1b?auto=format&fit=crop&w=800&q=90",purpose:"Demo cold-care category product.",guide:["Check active ingredients to avoid accidental duplication.","Read age restrictions and warnings.","Ask a pharmacist if unsure."]}
];
let cart=JSON.parse(localStorage.getItem("medix-cart")||"[]");
const grid=document.getElementById("medicineGrid"),toast=document.getElementById("toast");
const money=n=>"₹"+n.toLocaleString("en-IN");
function notify(x){toast.textContent=x;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
function render(list=meds){grid.innerHTML=list.map((m,i)=>`<article class="medicine reveal visible"><div class="med-img"><img loading="lazy" src="${m.img}" alt="${m.name}"><button onclick="medicineInfo(${meds.indexOf(m)})">i</button></div><div class="med-body"><span class="pill">${m.cat}</span><h3>${m.name}</h3><p>${m.purpose}</p><div class="med-bottom"><b>${money(m.price)}</b><button class="add" onclick="add(${meds.indexOf(m)})">Add +</button></div></div></article>`).join("")}
render();
document.getElementById("filters").onclick=e=>{if(!e.target.dataset.cat)return;document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");const c=e.target.dataset.cat;render(c==="All"?meds:meds.filter(m=>m.cat===c))};
document.getElementById("allMeds").onclick=()=>{document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));document.querySelector('[data-cat="All"]').classList.add("active");render()};
function modal(x){document.getElementById("modalCard").innerHTML=x;document.getElementById("modal").classList.add("show")}function closeModal(){document.getElementById("modal").classList.remove("show")}
document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();closeCart()}})
function medicineInfo(i){const m=meds[i];modal(`<button class="close" onclick="closeModal()">×</button><img src="${m.img}" style="width:100%;height:220px;object-fit:cover;border-radius:16px" alt="${m.name}"><span class="pill" style="margin-top:15px">${m.cat}</span><h2>${m.name}</h2><p>${m.purpose}</p><div class="info"><b>Guidelines</b><ul style="padding-left:18px;margin-top:7px">${m.guide.map(g=>`<li>${g}</li>`).join("")}</ul></div><div class="info"><b>Important:</b> This is general educational information. Always follow the current product label and advice from your healthcare professional/pharmacist.</div><button class="btn primary" style="margin-top:15px" onclick="add(${i});closeModal()">Add to demo cart • ${money(m.price)}</button>`)}
function add(i){cart.push(meds[i]);localStorage.setItem("medix-cart",JSON.stringify(cart));updateCart();notify(meds[i].name+" added")}
function updateCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartItems").innerHTML=cart.length?cart.map((m,i)=>`<div class="cart-item"><img src="${m.img}" alt=""><div style="flex:1"><b>${m.name}</b><small>${money(m.price)}</small><button class="remove" onclick="removeItem(${i})">Remove</button></div></div>`).join(""):`<p style="color:var(--muted);padding:30px 0">No items yet.</p>`;document.getElementById("total").textContent=money(cart.reduce((s,m)=>s+m.price,0))}
function removeItem(i){cart.splice(i,1);localStorage.setItem("medix-cart",JSON.stringify(cart));updateCart()}
updateCart();document.getElementById("cartBtn").onclick=()=>document.getElementById("drawer").classList.add("open");function closeCart(){document.getElementById("drawer").classList.remove("open")}
function searchNow(){const q=document.getElementById("search").value.toLowerCase().trim();if(!q){notify("Type a medicine, service or topic");return}const f=meds.filter(m=>(m.name+" "+m.cat+" "+m.purpose).toLowerCase().includes(q));render(f);document.getElementById("medicines").scrollIntoView({behavior:"smooth"});notify(f.length?`${f.length} result(s) found`:"No medicine matched in this demo catalogue")}
document.getElementById("searchBtn").onclick=searchNow;document.getElementById("search").onkeydown=e=>{if(e.key==="Enter")searchNow()};
function appointment(spec="General Physician"){modal(`<button class="close" onclick="closeModal()">×</button><h2>Book a consultation</h2><p>Choose a speciality and date. This is a demo booking interface.</p><div class="modal-grid"><input placeholder="Full name"><select><option ${spec==="General Physician"?"selected":""}>General Physician</option><option ${spec==="Dermatologist"?"selected":""}>Dermatologist</option><option ${spec==="Cardiologist"?"selected":""}>Cardiologist</option><option ${spec==="Pediatrician"?"selected":""}>Pediatrician</option><option>Neurologist</option><option>Gastroenterologist</option></select><input type="date"><select><option>Video consultation</option><option>In-person</option></select></div><button class="btn primary" style="margin-top:15px" onclick="notify('Appointment request submitted (demo)');closeModal()">Request appointment</button>`)}
function bmi(){modal(`<button class="close" onclick="closeModal()">×</button><h2>BMI calculator</h2><p>BMI is a screening measure, not a diagnosis.</p><div class="modal-grid"><input id="bh" type="number" placeholder="Height (cm)"><input id="bw" type="number" placeholder="Weight (kg)"></div><button class="btn primary" style="margin-top:15px" onclick="calcBMI()">Calculate</button><div id="bout" class="info" style="display:none"></div>`)}
function calcBMI(){let h=+bh.value,w=+bw.value;if(!h||!w){notify("Enter both values");return}let b=w/(h/100)**2;bout.style.display="block";bout.innerHTML=`<b>BMI: ${b.toFixed(1)}</b><br>${b<18.5?"Below the commonly used adult range":b<25?"Within the commonly used adult range":b<30?"Above the commonly used adult range":"High range"}. For personal interpretation, speak with a clinician.`}
function reminder(){modal(`<button class="close" onclick="closeModal()">×</button><h2>Medicine reminder</h2><p>Demo reminder while this browser tab remains open.</p><div class="modal-grid"><input id="rn" placeholder="Medicine name"><input id="rt" type="time"></div><button class="btn primary" style="margin-top:15px" onclick="setReminder()">Set reminder</button>`)}
function setReminder(){let t=rt.value;if(!t){notify("Choose a time");return}let [h,m]=t.split(":").map(Number),d=new Date();d.setHours(h,m,0,0);if(d<=new Date())d.setDate(d.getDate()+1);let n=rn.value||"your medicine";setTimeout(()=>notify("⏰ Reminder: "+n),d-Date.now());closeModal();notify("Reminder set for "+t)}
function firstAid(){modal(`<button class="close" onclick="closeModal()">×</button><h2>Basic first-aid guide</h2><div class="modal-grid"><div class="info"><b>Minor cut</b><br>Clean gently and protect with an appropriate dressing. Seek care for serious wounds or uncontrolled bleeding.</div><div class="info"><b>Minor burn</b><br>Cool under clean running water. Seek medical help for serious or extensive burns.</div><div class="info"><b>Nosebleed</b><br>Sit upright, lean forward and gently pinch the soft part of the nose.</div><div class="info"><b>Emergency</b><br>Severe breathing difficulty, unconsciousness or severe bleeding requires urgent medical help.</div></div>`)}
function emergency(){modal(`<button class="close" onclick="closeModal()">×</button><h2>Urgent help</h2><p>If you think someone is in immediate danger, contact your local emergency service or go to an emergency department.</p><div class="info"><b>Do not use this website to delay emergency care.</b><br>Examples of urgent warning signs can include severe difficulty breathing, loss of consciousness, severe bleeding, or other life-threatening symptoms.</div><button class="btn emergency-btn" style="margin-top:15px" onclick="closeModal()">I understand</button>`)}
document.querySelectorAll(".quick-tools button").forEach(b=>b.onclick=()=>{const t=b.dataset.tool;if(t==="search")document.getElementById("search").focus();if(t==="doctor")appointment();if(t==="reminder")reminder();if(t==="emergency")emergency()});
document.querySelectorAll(".service").forEach(s=>s.onclick=()=>{let a=s.dataset.action;if(a==="bmi")bmi();if(a==="reminder")reminder();if(a==="doctor")appointment();if(a==="firstaid")firstAid()});
document.getElementById("startGuide").onclick=()=>document.getElementById("safety").scrollIntoView({behavior:"smooth"});
document.querySelectorAll(".moment").forEach(m=>m.onclick=()=>{document.querySelectorAll(".moment").forEach(x=>x.classList.remove("active"));m.classList.add("active")});
const instructionData={medicine:["Taking a medicine — simple checklist","1. Confirm the medicine name and active ingredient. 2. Read the current label. 3. Check dose/timing exactly as directed. 4. Check warnings and interactions. 5. Ask a pharmacist/clinician if unsure. 6. Store and dispose according to instructions."],prescription:["Prescription checklist","1. Keep the prescription and medicine list together. 2. Check the medicine name and strength when you receive it. 3. Ask what it is for and how/when to take it. 4. Ask about interactions and side effects. 5. Keep follow-up instructions."],appointment:["Appointment checklist","1. Write down your main concern. 2. Bring your current medicine list. 3. Bring relevant reports/prescriptions if requested. 4. Mention allergies or previous reactions. 5. Ask what to do next and when to follow up."],emergency:["Urgent symptoms","If there is severe difficulty breathing, loss of consciousness, severe bleeding or another life-threatening emergency, seek emergency medical help immediately rather than relying on this site."]};
document.querySelectorAll("[data-instruction]").forEach(b=>b.onclick=()=>{let x=instructionData[b.dataset.instruction];modal(`<button class="close" onclick="closeModal()">×</button><span class="eyebrow">STEP-BY-STEP</span><h2>${x[0]}</h2><p>${x[1]}</p><div class="info">Educational guidance only. Follow professional advice and product-specific instructions where applicable.</div>`)});
const guideText={hydration:["Hydration","Regular fluid intake supports normal body functions. Needs vary with activity, environment and individual health circumstances."],sleep:["Sleep routine","A consistent schedule, a comfortable sleep environment and a wind-down routine can support healthier sleep habits."],medicine:["Medicine safety","Know the medicine, check the label and ask a professional when uncertain. WHO's medication-safety campaign uses the “KNOW. CHECK. ASK.” approach. citeturn0search0"],storage:["Medicine storage","Follow the product-specific storage instructions. Keep medicines appropriately stored and away from children when applicable; check official product guidance for disposal. citeturn0search3turn0search12"]};
document.querySelectorAll("[data-guide]").forEach(b=>b.onclick=()=>{let x=guideText[b.dataset.guide];modal(`<button class="close" onclick="closeModal()">×</button><span class="eyebrow">HEALTH HUB</span><h2>${x[0]}</h2><p>${x[1]}</p><div class="info">For individual advice, speak with a qualified healthcare professional.</div>`)});
document.querySelectorAll(".faq-list button").forEach(b=>b.onclick=()=>b.classList.toggle("open"));document.getElementById("emergencyBtn").onclick=emergency;
document.getElementById("contactForm").onsubmit=e=>{e.preventDefault();notify("Message submitted successfully (demo)");e.target.reset()};
document.getElementById("theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light");theme.textContent=document.body.classList.contains("dark")?"☾":"☼"};if(localStorage.getItem("theme")==="dark"){document.body.classList.add("dark");theme.textContent="☾"}
mobile.onclick=()=>nav.classList.toggle("open");document.querySelectorAll("#nav a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>observer.observe(e));addEventListener("scroll",()=>progress.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+"%");
